FROM debian:11
RUN apt-get update && apt-get install -y libgtk-3-dev curl git clang cmake ninja-build pkg-config unzip xz-utils zip libglu1-mesa openjdk-17-jdk
RUN git clone https://github.com/flutter/flutter.git -b stable /flutter
ENV PATH="/flutter/bin:/flutter/bin/cache/dart-sdk/bin:${PATH}"
WORKDIR /app
RUN flutter doctor